### ISSUE TITLE
Error HTTP 500 while generating form : Unrecognized Type

### ISSUE THREAD

**Issue by bhattchaitanya** [davidmoten/xsd-forms#17]
This is the below form 
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns="http://www.irs.gov/efile" xmlns:xs="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.irs.gov/efile" elementFormDefault="qualified" attributeFormDefault="unqualified" version="1.0">

	<xs:annotation>
		<xs:documentation>
			<Description>IRS e-file Schema - Basic Adjustment Under Section 367(a)(5) Statement</Description>
			<TaxYear>2014</TaxYear>
			<MaturityLevel>Final Release</MaturityLevel>
			<ReleaseDate>December 23, 2014</ReleaseDate>
		</xs:documentation>
	</xs:annotation>

	<xs:include schemaLocation="../../../Common/efileTypes.xs"/>

	
	
	

	<xs:element name="BscAdjUnderSect367a5Stmt">
		<xs:annotation>
			<xs:documentation>Basic Adjustment Under Section 367(a)(5) Statement</xs:documentation>
		</xs:annotation>
		<xs:complexType>
			<xs:complexContent>
				<xs:extension base="BscAdjUnderSect367a5StmtType">
					<xs:attributeGroup ref="DocumentAttributes">
						<xs:annotation>
							<xs:documentation>Common return document attributes</xs:documentation>
						</xs:annotation>
					</xs:attributeGroup>
					<xs:attribute name="documentName" type="xs:string" fixed="BasicAdjustmentUnderSection367a5Statement">
						<xs:annotation>
							<xs:documentation>IRS internal use only. To avoid error in the return, do not include the attribute name or value.</xs:documentation>
						</xs:annotation>
					</xs:attribute>
				</xs:extension>
			</xs:complexContent>
		</xs:complexType>
	</xs:element>

	<xs:complexType name="BscAdjUnderSect367a5StmtType">
		<xs:annotation>
			<xs:documentation>Content model for Basic Adjustment Under Section 367(a)(5) Statement</xs:documentation>
		</xs:annotation>

		<xs:sequence>

			
			<xs:element name="BasicAdjUnderSect367a5InfoGrp" type="BasicAdjUnderSect367a5InfoGrpType" minOccurs="0" maxOccurs="unbounded">
				<xs:annotation>
					<xs:documentation>
						<Description>Basic Adjustment Under Section 367(a)(5) Statement</Description>
					</xs:documentation>
				</xs:annotation>
			</xs:element>

		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="BasicAdjUnderSect367a5InfoGrpType">
		<xs:annotation>
			<xs:documentation>Content model for basic adjustment under section 367(a)(5) info</xs:documentation>
		</xs:annotation>

		<xs:sequence>

			
			<xs:element name="AssetTransferredInExchangeDesc" type="LineExplanationType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						<Description>Description of the asset tranferred in the exchange</Description>
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			
			<xs:element name="CondSect367a5RegsBeenStsfdInd" type="BooleanType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						<Description>Have the conditions set forth in the second sentence of Section 367(a)(5) and any regulations under that section been satisfied?</Description>
					</xs:documentation>
				</xs:annotation>
			</xs:element>

			
			<xs:element name="AdjustmentMadeSect367a5Desc" type="ShortExplanationType" minOccurs="0">
				<xs:annotation>
					<xs:documentation>
						<Description>Enter an explanation of any basis or other adjustments made pursuant to Section 367(a)(5) and any regulations thereunder</Description>
					</xs:documentation>
				</xs:annotation>
			</xs:element>

		</xs:sequence>

	</xs:complexType>

</xs:schema>

This is the error :
HTTP ERROR 500

Problem accessing /generate. Reason:

    Server Error
Caused by:

java.lang.RuntimeException: unrecognized type: {http://www.irs.gov/efile}LineExplanationType
	at com.github.davidmoten.xsdforms.tree.Util$.unexpected(util.scala:23)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.getType(traversor.scala:70)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:135)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.com$github$davidmoten$xsdforms$tree$SchemaTraversor$$process(traversor.scala:280)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor$$anonfun$process$2.apply(traversor.scala:231)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor$$anonfun$process$2.apply(traversor.scala:231)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:231)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.com$github$davidmoten$xsdforms$tree$SchemaTraversor$$process(traversor.scala:191)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:180)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:155)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:135)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.com$github$davidmoten$xsdforms$tree$SchemaTraversor$$process(traversor.scala:280)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor$$anonfun$process$2.apply(traversor.scala:231)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor$$anonfun$process$2.apply(traversor.scala:231)
	at scala.collection.immutable.List.foreach(List.scala:318)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:231)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.com$github$davidmoten$xsdforms$tree$SchemaTraversor$$process(traversor.scala:191)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:180)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:155)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:215)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:206)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:167)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.process(traversor.scala:140)
	at com.github.davidmoten.xsdforms.tree.SchemaTraversor.traverse(traversor.scala:93)
	at com.github.davidmoten.xsdforms.Generator$.generateHtmlAsString(generator.scala:137)
	at com.github.davidmoten.xsdforms.Generator$.generateHtml(generator.scala:111)
	at com.github.davidmoten.xsdforms.Generator.generateHtml(generator.scala)
	at com.github.davidmoten.xsdforms.servlet.GeneratorServlet.returnHtml(GeneratorServlet.java:53)
	at com.github.davidmoten.xsdforms.servlet.GeneratorServlet.doPost(GeneratorServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:722)

**Comment by davidmoten** [comment]
Hi, only a limited subset of xsd is supported. Check README.MD for details.
Cheers
Dave
