### ISSUE TITLE
Online Webservice: java.lang.OutOfMemoryError: Java heap space

### ISSUE THREAD

**Issue by tfazionato** [davidmoten/xsd-forms#22]
Hi,

Informing an xsd in the online service, I am getting the following message: java.lang.OutOfMemoryError: Java heap space. 

You could increase the memory of the online service?

Grateful.

**Comment by tfazionato** [comment]
java.lang.OutOfMemoryError: Java heap space
	at java.util.Arrays.copyOf(Arrays.java:3332)
	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:137)
	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:121)
	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:421)
	at java.lang.StringBuffer.append(StringBuffer.java:272)
	at com.github.davidmoten.xsdforms.tree.html.Html.append(html.scala:150)
	at com.github.davidmoten.xsdforms.tree.html.Html.elementBase(html.scala:138)
	at com.github.davidmoten.xsdforms.tree.html.Html.element(html.scala:128)
	at com.github.davidmoten.xsdforms.tree.html.Html.input(html.scala:97)
	at com.github.davidmoten.xsdforms.tree.FormCreator.addTextFieldOrCheckbox(form-creator.scala:494)
	at com.github.davidmoten.xsdforms.tree.FormCreator.addTextOrCheckbox(form-creator.scala:473)
	at com.github.davidmoten.xsdforms.tree.FormCreator.addInput(form-creator.scala:461)
	at com.github.davidmoten.xsdforms.tree.FormCreator.com$github$davidmoten$xsdforms$tree$FormCreator$$simpleType(form-creator.scala:427)
	at com.github.davidmoten.xsdforms.tree.FormCreator$$anonfun$doNode$3.apply(form-creator.scala:178)
	at com.github.davidmoten.xsdforms.tree.FormCreator$$anonfun$doNode$3.apply(form-creator.scala:171)
	at scala.collection.immutable.Range.foreach(Range.scala:141)
	at com.github.davidmoten.xsdforms.tree.FormCreator.doNode(form-creator.scala:171)
	at com.github.davidmoten.xsdforms.tree.FormCreator.com$github$davidmoten$xsdforms$tree$FormCreator$$doNode(form-creator.scala:46)
	at com.github.davidmoten.xsdforms.tree.FormCreator$$anonfun$com$github$davidmoten$xsdforms$tree$FormCreator$$doInstance$1.apply(form-creator.scala:93)
	at com.github.davidmoten.xsdforms.tree.FormCreator$$anonfun$com$github$davidmoten$xsdforms$tree$FormCreator$$doInstance$1.apply(form-creator.scala:93)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:60)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
	at com.github.davidmoten.xsdforms.tree.FormCreator.com$github$davidmoten$xsdforms$tree$FormCreator$$doInstance(form-creator.scala:93)
	at com.github.davidmoten.xsdforms.tree.FormCreator$$anonfun$doNode$1.apply$mcVI$sp(form-creator.scala:69)
	at scala.collection.immutable.Range.foreach$mVc$sp(Range.scala:141)
	at com.github.davidmoten.xsdforms.tree.FormCreator.doNode(form-creator.scala:68)
	at com.github.davidmoten.xsdforms.tree.FormCreator.com$github$davidmoten$xsdforms$tree$FormCreator$$doNode(form-creator.scala:47)
	at com.github.davidmoten.xsdforms.tree.FormCreator$$anonfun$com$github$davidmoten$xsdforms$tree$FormCreator$$doInstance$1.apply(form-creator.scala:93)
	at com.github.davidmoten.xsdforms.tree.FormCreator$$anonfun$com$github$davidmoten$xsdforms$tree$FormCreator$$doInstance$1.apply(form-creator.scala:93)
	at scala.collection.LinearSeqOptimized$class.foreach(LinearSeqOptimized.scala:60)
	at scala.collection.mutable.MutableList.foreach(MutableList.scala:30)
	at com.github.davidmoten.xsdforms.tree.FormCreator.com

**Comment by davidmoten** [comment]
Hi, I don't think so because is free heroku  paas but is easy to run
locally. Just check the readme.
Cheers
Dave

**Comment by KinomaMJ** [comment]
I encountered the same http500 as above so I followed the excellent instructions in the readme on running it locally.  All builds and all artifacts appear to have succeeded.  But when I run xsd-forms-generator-webapp, it runs fine till I hit Generate, and then I get a different error:

```
2016-10-18 14:20:38.641:WARN:oejs.ServletHandler:/generate
java.util.NoSuchElementException: None.get
	at scala.None$.get(Option.scala:313)
	at scala.None$.get(Option.scala:311)
	at com.github.davidmoten.xsdforms.Generator$.generateHtmlAsString(generator.scala:133)
	at com.github.davidmoten.xsdforms.Generator$.generateHtml(generator.scala:111)
	at com.github.davidmoten.xsdforms.Generator.generateHtml(generator.scala)
	at com.github.davidmoten.xsdforms.servlet.GeneratorServlet.returnHtml(GeneratorServlet.java:53)
	at com.github.davidmoten.xsdforms.servlet.GeneratorServlet.doPost(GeneratorServlet.java:36)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:755)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:501)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:255)
	at org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:154)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
	at java.lang.Thread.run(Thread.java:745)
```
